use num_derive::{FromPrimitive, ToPrimitive};
use std::fmt::{Display, Formatter, Result};

#[derive(Debug, FromPrimitive, ToPrimitive, Clone, Copy)]
#[repr(u8)]
#[allow(non_camel_case_types)]
pub enum Opcode {
    // ===== 0x0X =====
    Nop = 0x00,
    Ld_Bc_d16 = 0x01,
    Ld_BCref_A = 0x02,
    Inc_Bc = 0x03,
    Inc_B = 0x04,
    Dec_B = 0x05,
    Ld_B_d8 = 0x06,
    Rlca = 0x07,
    Ld_a16ref_Sp = 0x08,
    Add_Hl_Bc = 0x09,
    Ld_A_BCref = 0x0A,
    Dec_Bc = 0x0B,
    Inc_C = 0x0C,
    Dec_C = 0x0D,
    Ld_C_d8 = 0x0E,
    Rrca = 0x0F,

    // ===== 0x1X =====
    Stop = 0x10,
    Ld_De_d16 = 0x11,
    Ld_DEref_A = 0x12,
    Inc_De = 0x13,
    Inc_D = 0x14,
    Dec_D = 0x15,
    Ld_D_d8 = 0x16,
    Rla = 0x17,
    Jr_r8 = 0x18,
    Add_Hl_De = 0x19,
    Ld_A_DEref = 0x1A,
    Dec_De = 0x1B,
    Inc_E = 0x1C,
    Dec_E = 0x1D,
    Ld_E_d8 = 0x1E,
    Rra = 0x1F,

    // ===== 0x2X =====
    Jr_Nz_r8 = 0x20,
    Ld_Hl_d16 = 0x21,
    Ld_HLIref_A = 0x22,
    Inc_Hl = 0x23,
    Inc_H = 0x24,
    Dec_H = 0x25,
    Ld_H_d8 = 0x26,
    Daa = 0x27,
    Jr_Z_r8 = 0x28,
    Add_Hl_Hl = 0x29,
    Ld_A_HLIref = 0x2A,
    Dec_Hl = 0x2B,
    Inc_L = 0x2C,
    Dec_L = 0x2D,
    Ld_L_d8 = 0x2E,
    Cpl = 0x2F,

    // ===== 0x3X =====
    Jr_Nc_r8 = 0x30,
    Ld_Sp_d16 = 0x31,
    Ld_HLDref_A = 0x32,
    Inc_Sp = 0x33,
    Inc_HLref = 0x34,
    Dec_HLref = 0x35,
    Ld_HLref_d8 = 0x36,
    Scf = 0x37,
    Jr_C_r8 = 0x38,
    Add_Hl_Sp = 0x39,
    Ld_A_HLDref = 0x3A,
    Dec_Sp = 0x3B,
    Inc_A = 0x3C,
    Dec_A = 0x3D,
    Ld_A_d8 = 0x3E,
    Ccf = 0x3F,

    // ===== 0x4X - LD B/C,r =====
    Ld_B_B = 0x40,
    Ld_B_C = 0x41,
    Ld_B_D = 0x42,
    Ld_B_E = 0x43,
    Ld_B_H = 0x44,
    Ld_B_L = 0x45,
    Ld_B_HLref = 0x46,
    Ld_B_A = 0x47,
    Ld_C_B = 0x48,
    Ld_C_C = 0x49,
    Ld_C_D = 0x4A,
    Ld_C_E = 0x4B,
    Ld_C_H = 0x4C,
    Ld_C_L = 0x4D,
    Ld_C_HLref = 0x4E,
    Ld_C_A = 0x4F,

    // ===== 0x5X - LD D/E,r =====
    Ld_D_B = 0x50,
    Ld_D_C = 0x51,
    Ld_D_D = 0x52,
    Ld_D_E = 0x53,
    Ld_D_H = 0x54,
    Ld_D_L = 0x55,
    Ld_D_HLref = 0x56,
    Ld_D_A = 0x57,
    Ld_E_B = 0x58,
    Ld_E_C = 0x59,
    Ld_E_D = 0x5A,
    Ld_E_E = 0x5B,
    Ld_E_H = 0x5C,
    Ld_E_L = 0x5D,
    Ld_E_HLref = 0x5E,
    Ld_E_A = 0x5F,

    // ===== 0x6X - LD H/L,r =====
    Ld_H_B = 0x60,
    Ld_H_C = 0x61,
    Ld_H_D = 0x62,
    Ld_H_E = 0x63,
    Ld_H_H = 0x64,
    Ld_H_L = 0x65,
    Ld_H_HLref = 0x66,
    Ld_H_A = 0x67,
    Ld_L_B = 0x68,
    Ld_L_C = 0x69,
    Ld_L_D = 0x6A,
    Ld_L_E = 0x6B,
    Ld_L_H = 0x6C,
    Ld_L_L = 0x6D,
    Ld_L_HLref = 0x6E,
    Ld_L_A = 0x6F,

    // ===== 0x7X - LD (HL)/A,r =====
    Ld_HLref_B = 0x70,
    Ld_HLref_C = 0x71,
    Ld_HLref_D = 0x72,
    Ld_HLref_E = 0x73,
    Ld_HLref_H = 0x74,
    Ld_HLref_L = 0x75,
    Halt = 0x76,
    Ld_HLref_A = 0x77,
    Ld_A_B = 0x78,
    Ld_A_C = 0x79,
    Ld_A_D = 0x7A,
    Ld_A_E = 0x7B,
    Ld_A_H = 0x7C,
    Ld_A_L = 0x7D,
    Ld_A_HLref = 0x7E,
    Ld_A_A = 0x7F,

    // ===== 0x8X - ADD/ADC A,r =====
    Add_A_B = 0x80,
    Add_A_C = 0x81,
    Add_A_D = 0x82,
    Add_A_E = 0x83,
    Add_A_H = 0x84,
    Add_A_L = 0x85,
    Add_A_HLref = 0x86,
    Add_A_A = 0x87,
    Adc_A_B = 0x88,
    Adc_A_C = 0x89,
    Adc_A_D = 0x8A,
    Adc_A_E = 0x8B,
    Adc_A_H = 0x8C,
    Adc_A_L = 0x8D,
    Adc_A_HLref = 0x8E,
    Adc_A_A = 0x8F,

    // ===== 0x9X - SUB/SBC A,r =====
    Sub_A_B = 0x90,
    Sub_A_C = 0x91,
    Sub_A_D = 0x92,
    Sub_A_E = 0x93,
    Sub_A_H = 0x94,
    Sub_A_L = 0x95,
    Sub_A_HLref = 0x96,
    Sub_A_A = 0x97,
    Sbc_A_B = 0x98,
    Sbc_A_C = 0x99,
    Sbc_A_D = 0x9A,
    Sbc_A_E = 0x9B,
    Sbc_A_H = 0x9C,
    Sbc_A_L = 0x9D,
    Sbc_A_HLref = 0x9E,
    Sbc_A_A = 0x9F,

    // ===== 0xAX - AND/XOR A,r =====
    And_A_B = 0xA0,
    And_A_C = 0xA1,
    And_A_D = 0xA2,
    And_A_E = 0xA3,
    And_A_H = 0xA4,
    And_A_L = 0xA5,
    And_A_HLref = 0xA6,
    And_A_A = 0xA7,
    Xor_A_B = 0xA8,
    Xor_A_C = 0xA9,
    Xor_A_D = 0xAA,
    Xor_A_E = 0xAB,
    Xor_A_H = 0xAC,
    Xor_A_L = 0xAD,
    Xor_A_HLref = 0xAE,
    Xor_A_A = 0xAF,

    // ===== 0xBX - OR/CP A,r =====
    Or_A_B = 0xB0,
    Or_A_C = 0xB1,
    Or_A_D = 0xB2,
    Or_A_E = 0xB3,
    Or_A_H = 0xB4,
    Or_A_L = 0xB5,
    Or_A_HLref = 0xB6,
    Or_A_A = 0xB7,
    Cp_A_B = 0xB8,
    Cp_A_C = 0xB9,
    Cp_A_D = 0xBA,
    Cp_A_E = 0xBB,
    Cp_A_H = 0xBC,
    Cp_A_L = 0xBD,
    Cp_A_HLref = 0xBE,
    Cp_A_A = 0xBF,

    // ===== 0xCX - Control flow, stack, immediate ALU =====
    Ret_Nz = 0xC0,
    Pop_Bc = 0xC1,
    Jp_Nz_a16 = 0xC2,
    Jp_a16 = 0xC3,
    Call_Nz_a16 = 0xC4,
    Push_Bc = 0xC5,
    Add_A_d8 = 0xC6,
    Rst_00 = 0xC7,
    Ret_Z = 0xC8,
    Ret = 0xC9,
    Jp_Z_a16 = 0xCA,
    Prefix_Cb = 0xCB,
    Call_Z_a16 = 0xCC,
    Call_a16 = 0xCD,
    Adc_A_d8 = 0xCE,
    Rst_08 = 0xCF,

    // ===== 0xDX - More control flow =====
    Ret_Nc = 0xD0,
    Pop_De = 0xD1,
    Jp_Nc_a16 = 0xD2,
    // 0xD3 - unused
    Call_Nc_a16 = 0xD4,
    Push_De = 0xD5,
    Sub_A_d8 = 0xD6,
    Rst_10 = 0xD7,
    Ret_C = 0xD8,
    Reti = 0xD9,
    Jp_C_a16 = 0xDA,
    // 0xDB - unused
    Call_C_a16 = 0xDC,
    // 0xDD - unused
    Sbc_A_d8 = 0xDE,
    Rst_18 = 0xDF,

    // ===== 0xEX - I/O, stack, JP =====
    Ldh_a8ref_A = 0xE0,
    Pop_Hl = 0xE1,
    Ld_Cref_A = 0xE2,
    // 0xE3 - unused
    // 0xE4 - unused
    Push_Hl = 0xE5,
    And_A_d8 = 0xE6,
    Rst_20 = 0xE7,
    Add_Sp_r8 = 0xE8,
    Jp_Hl = 0xE9,
    Ld_a16ref_A = 0xEA,
    // 0xEB - unused
    // 0xEC - unused
    // 0xED - unused
    Xor_A_d8 = 0xEE,
    Rst_28 = 0xEF,

    // ===== 0xFX - I/O, stack, misc =====
    Ldh_A_a8ref = 0xF0,
    Pop_Af = 0xF1,
    Ld_A_Cref = 0xF2,
    Di = 0xF3,
    // 0xF4 - unused
    Push_Af = 0xF5,
    Or_A_d8 = 0xF6,
    Rst_30 = 0xF7,
    Ld_Hl_SpPlusr8 = 0xF8,
    Ld_Sp_Hl = 0xF9,
    Ld_A_a16ref = 0xFA,
    Ei = 0xFB,
    // 0xFC - unused
    // 0xFD - unused
    Cp_A_d8 = 0xFE,
    Rst_38 = 0xFF,
}

impl Display for Opcode {
    fn fmt(&self, f: &mut Formatter) -> Result {
        let name = match self {
            // 0x0X
            Opcode::Nop => "NOP",
            Opcode::Ld_Bc_d16 => "LD BC,d16",
            Opcode::Ld_BCref_A => "LD (BC),A",
            Opcode::Inc_Bc => "INC BC",
            Opcode::Inc_B => "INC B",
            Opcode::Dec_B => "DEC B",
            Opcode::Ld_B_d8 => "LD B,d8",
            Opcode::Rlca => "RLCA",
            Opcode::Ld_a16ref_Sp => "LD (a16),SP",
            Opcode::Add_Hl_Bc => "ADD HL,BC",
            Opcode::Ld_A_BCref => "LD A,(BC)",
            Opcode::Dec_Bc => "DEC BC",
            Opcode::Inc_C => "INC C",
            Opcode::Dec_C => "DEC C",
            Opcode::Ld_C_d8 => "LD C,d8",
            Opcode::Rrca => "RRCA",

            // 0x1X
            Opcode::Stop => "STOP",
            Opcode::Ld_De_d16 => "LD DE,d16",
            Opcode::Ld_DEref_A => "LD (DE),A",
            Opcode::Inc_De => "INC DE",
            Opcode::Inc_D => "INC D",
            Opcode::Dec_D => "DEC D",
            Opcode::Ld_D_d8 => "LD D,d8",
            Opcode::Rla => "RLA",
            Opcode::Jr_r8 => "JR r8",
            Opcode::Add_Hl_De => "ADD HL,DE",
            Opcode::Ld_A_DEref => "LD A,(DE)",
            Opcode::Dec_De => "DEC DE",
            Opcode::Inc_E => "INC E",
            Opcode::Dec_E => "DEC E",
            Opcode::Ld_E_d8 => "LD E,d8",
            Opcode::Rra => "RRA",

            // 0x2X
            Opcode::Jr_Nz_r8 => "JR NZ,r8",
            Opcode::Ld_Hl_d16 => "LD HL,d16",
            Opcode::Ld_HLIref_A => "LD (HL+),A",
            Opcode::Inc_Hl => "INC HL",
            Opcode::Inc_H => "INC H",
            Opcode::Dec_H => "DEC H",
            Opcode::Ld_H_d8 => "LD H,d8",
            Opcode::Daa => "DAA",
            Opcode::Jr_Z_r8 => "JR Z,r8",
            Opcode::Add_Hl_Hl => "ADD HL,HL",
            Opcode::Ld_A_HLIref => "LD A,(HL+)",
            Opcode::Dec_Hl => "DEC HL",
            Opcode::Inc_L => "INC L",
            Opcode::Dec_L => "DEC L",
            Opcode::Ld_L_d8 => "LD L,d8",
            Opcode::Cpl => "CPL",

            // 0x3X
            Opcode::Jr_Nc_r8 => "JR NC,r8",
            Opcode::Ld_Sp_d16 => "LD SP,d16",
            Opcode::Ld_HLDref_A => "LD (HL-),A",
            Opcode::Inc_Sp => "INC SP",
            Opcode::Inc_HLref => "INC (HL)",
            Opcode::Dec_HLref => "DEC (HL)",
            Opcode::Ld_HLref_d8 => "LD (HL),d8",
            Opcode::Scf => "SCF",
            Opcode::Jr_C_r8 => "JR C,r8",
            Opcode::Add_Hl_Sp => "ADD HL,SP",
            Opcode::Ld_A_HLDref => "LD A,(HL-)",
            Opcode::Dec_Sp => "DEC SP",
            Opcode::Inc_A => "INC A",
            Opcode::Dec_A => "DEC A",
            Opcode::Ld_A_d8 => "LD A,d8",
            Opcode::Ccf => "CCF",

            // 0x4X
            Opcode::Ld_B_B => "LD B,B",
            Opcode::Ld_B_C => "LD B,C",
            Opcode::Ld_B_D => "LD B,D",
            Opcode::Ld_B_E => "LD B,E",
            Opcode::Ld_B_H => "LD B,H",
            Opcode::Ld_B_L => "LD B,L",
            Opcode::Ld_B_HLref => "LD B,(HL)",
            Opcode::Ld_B_A => "LD B,A",
            Opcode::Ld_C_B => "LD C,B",
            Opcode::Ld_C_C => "LD C,C",
            Opcode::Ld_C_D => "LD C,D",
            Opcode::Ld_C_E => "LD C,E",
            Opcode::Ld_C_H => "LD C,H",
            Opcode::Ld_C_L => "LD C,L",
            Opcode::Ld_C_HLref => "LD C,(HL)",
            Opcode::Ld_C_A => "LD C,A",

            // 0x5X
            Opcode::Ld_D_B => "LD D,B",
            Opcode::Ld_D_C => "LD D,C",
            Opcode::Ld_D_D => "LD D,D",
            Opcode::Ld_D_E => "LD D,E",
            Opcode::Ld_D_H => "LD D,H",
            Opcode::Ld_D_L => "LD D,L",
            Opcode::Ld_D_HLref => "LD D,(HL)",
            Opcode::Ld_D_A => "LD D,A",
            Opcode::Ld_E_B => "LD E,B",
            Opcode::Ld_E_C => "LD E,C",
            Opcode::Ld_E_D => "LD E,D",
            Opcode::Ld_E_E => "LD E,E",
            Opcode::Ld_E_H => "LD E,H",
            Opcode::Ld_E_L => "LD E,L",
            Opcode::Ld_E_HLref => "LD E,(HL)",
            Opcode::Ld_E_A => "LD E,A",

            // 0x6X
            Opcode::Ld_H_B => "LD H,B",
            Opcode::Ld_H_C => "LD H,C",
            Opcode::Ld_H_D => "LD H,D",
            Opcode::Ld_H_E => "LD H,E",
            Opcode::Ld_H_H => "LD H,H",
            Opcode::Ld_H_L => "LD H,L",
            Opcode::Ld_H_HLref => "LD H,(HL)",
            Opcode::Ld_H_A => "LD H,A",
            Opcode::Ld_L_B => "LD L,B",
            Opcode::Ld_L_C => "LD L,C",
            Opcode::Ld_L_D => "LD L,D",
            Opcode::Ld_L_E => "LD L,E",
            Opcode::Ld_L_H => "LD L,H",
            Opcode::Ld_L_L => "LD L,L",
            Opcode::Ld_L_HLref => "LD L,(HL)",
            Opcode::Ld_L_A => "LD L,A",

            // 0x7X
            Opcode::Ld_HLref_B => "LD (HL),B",
            Opcode::Ld_HLref_C => "LD (HL),C",
            Opcode::Ld_HLref_D => "LD (HL),D",
            Opcode::Ld_HLref_E => "LD (HL),E",
            Opcode::Ld_HLref_H => "LD (HL),H",
            Opcode::Ld_HLref_L => "LD (HL),L",
            Opcode::Halt => "HALT",
            Opcode::Ld_HLref_A => "LD (HL),A",
            Opcode::Ld_A_B => "LD A,B",
            Opcode::Ld_A_C => "LD A,C",
            Opcode::Ld_A_D => "LD A,D",
            Opcode::Ld_A_E => "LD A,E",
            Opcode::Ld_A_H => "LD A,H",
            Opcode::Ld_A_L => "LD A,L",
            Opcode::Ld_A_HLref => "LD A,(HL)",
            Opcode::Ld_A_A => "LD A,A",

            // 0x8X - ADD/ADC
            Opcode::Add_A_B => "ADD A,B",
            Opcode::Add_A_C => "ADD A,C",
            Opcode::Add_A_D => "ADD A,D",
            Opcode::Add_A_E => "ADD A,E",
            Opcode::Add_A_H => "ADD A,H",
            Opcode::Add_A_L => "ADD A,L",
            Opcode::Add_A_HLref => "ADD A,(HL)",
            Opcode::Add_A_A => "ADD A,A",
            Opcode::Adc_A_B => "ADC A,B",
            Opcode::Adc_A_C => "ADC A,C",
            Opcode::Adc_A_D => "ADC A,D",
            Opcode::Adc_A_E => "ADC A,E",
            Opcode::Adc_A_H => "ADC A,H",
            Opcode::Adc_A_L => "ADC A,L",
            Opcode::Adc_A_HLref => "ADC A,(HL)",
            Opcode::Adc_A_A => "ADC A,A",

            // 0x9X - SUB/SBC
            Opcode::Sub_A_B => "SUB A,B",
            Opcode::Sub_A_C => "SUB A,C",
            Opcode::Sub_A_D => "SUB A,D",
            Opcode::Sub_A_E => "SUB A,E",
            Opcode::Sub_A_H => "SUB A,H",
            Opcode::Sub_A_L => "SUB A,L",
            Opcode::Sub_A_HLref => "SUB A,(HL)",
            Opcode::Sub_A_A => "SUB A,A",
            Opcode::Sbc_A_B => "SBC A,B",
            Opcode::Sbc_A_C => "SBC A,C",
            Opcode::Sbc_A_D => "SBC A,D",
            Opcode::Sbc_A_E => "SBC A,E",
            Opcode::Sbc_A_H => "SBC A,H",
            Opcode::Sbc_A_L => "SBC A,L",
            Opcode::Sbc_A_HLref => "SBC A,(HL)",
            Opcode::Sbc_A_A => "SBC A,A",

            // 0xAX - AND/XOR
            Opcode::And_A_B => "AND A,B",
            Opcode::And_A_C => "AND A,C",
            Opcode::And_A_D => "AND A,D",
            Opcode::And_A_E => "AND A,E",
            Opcode::And_A_H => "AND A,H",
            Opcode::And_A_L => "AND A,L",
            Opcode::And_A_HLref => "AND A,(HL)",
            Opcode::And_A_A => "AND A,A",
            Opcode::Xor_A_B => "XOR A,B",
            Opcode::Xor_A_C => "XOR A,C",
            Opcode::Xor_A_D => "XOR A,D",
            Opcode::Xor_A_E => "XOR A,E",
            Opcode::Xor_A_H => "XOR A,H",
            Opcode::Xor_A_L => "XOR A,L",
            Opcode::Xor_A_HLref => "XOR A,(HL)",
            Opcode::Xor_A_A => "XOR A,A",

            // 0xBX - OR/CP
            Opcode::Or_A_B => "OR A,B",
            Opcode::Or_A_C => "OR A,C",
            Opcode::Or_A_D => "OR A,D",
            Opcode::Or_A_E => "OR A,E",
            Opcode::Or_A_H => "OR A,H",
            Opcode::Or_A_L => "OR A,L",
            Opcode::Or_A_HLref => "OR A,(HL)",
            Opcode::Or_A_A => "OR A,A",
            Opcode::Cp_A_B => "CP A,B",
            Opcode::Cp_A_C => "CP A,C",
            Opcode::Cp_A_D => "CP A,D",
            Opcode::Cp_A_E => "CP A,E",
            Opcode::Cp_A_H => "CP A,H",
            Opcode::Cp_A_L => "CP A,L",
            Opcode::Cp_A_HLref => "CP A,(HL)",
            Opcode::Cp_A_A => "CP A,A",

            // 0xCX
            Opcode::Ret_Nz => "RET NZ",
            Opcode::Pop_Bc => "POP BC",
            Opcode::Jp_Nz_a16 => "JP NZ,a16",
            Opcode::Jp_a16 => "JP a16",
            Opcode::Call_Nz_a16 => "CALL NZ,a16",
            Opcode::Push_Bc => "PUSH BC",
            Opcode::Add_A_d8 => "ADD A,d8",
            Opcode::Rst_00 => "RST 00H",
            Opcode::Ret_Z => "RET Z",
            Opcode::Ret => "RET",
            Opcode::Jp_Z_a16 => "JP Z,a16",
            Opcode::Prefix_Cb => "PREFIX CB",
            Opcode::Call_Z_a16 => "CALL Z,a16",
            Opcode::Call_a16 => "CALL a16",
            Opcode::Adc_A_d8 => "ADC A,d8",
            Opcode::Rst_08 => "RST 08H",

            // 0xDX
            Opcode::Ret_Nc => "RET NC",
            Opcode::Pop_De => "POP DE",
            Opcode::Jp_Nc_a16 => "JP NC,a16",
            Opcode::Call_Nc_a16 => "CALL NC,a16",
            Opcode::Push_De => "PUSH DE",
            Opcode::Sub_A_d8 => "SUB A,d8",
            Opcode::Rst_10 => "RST 10H",
            Opcode::Ret_C => "RET C",
            Opcode::Reti => "RETI",
            Opcode::Jp_C_a16 => "JP C,a16",
            Opcode::Call_C_a16 => "CALL C,a16",
            Opcode::Sbc_A_d8 => "SBC A,d8",
            Opcode::Rst_18 => "RST 18H",

            // 0xEX
            Opcode::Ldh_a8ref_A => "LDH (a8),A",
            Opcode::Pop_Hl => "POP HL",
            Opcode::Ld_Cref_A => "LD (C),A",
            Opcode::Push_Hl => "PUSH HL",
            Opcode::And_A_d8 => "AND A,d8",
            Opcode::Rst_20 => "RST 20H",
            Opcode::Add_Sp_r8 => "ADD SP,r8",
            Opcode::Jp_Hl => "JP HL",
            Opcode::Ld_a16ref_A => "LD (a16),A",
            Opcode::Xor_A_d8 => "XOR A,d8",
            Opcode::Rst_28 => "RST 28H",

            // 0xFX
            Opcode::Ldh_A_a8ref => "LDH A,(a8)",
            Opcode::Pop_Af => "POP AF",
            Opcode::Ld_A_Cref => "LD A,(C)",
            Opcode::Di => "DI",
            Opcode::Push_Af => "PUSH AF",
            Opcode::Or_A_d8 => "OR A,d8",
            Opcode::Rst_30 => "RST 30H",
            Opcode::Ld_Hl_SpPlusr8 => "LD HL,SP+r8",
            Opcode::Ld_Sp_Hl => "LD SP,HL",
            Opcode::Ld_A_a16ref => "LD A,(a16)",
            Opcode::Ei => "EI",
            Opcode::Cp_A_d8 => "CP A,d8",
            Opcode::Rst_38 => "RST 38H",
        };
        write!(f, "{}", name)
    }
}
